// Mock data for demo mode — used as fallback when backend API is unreachable.

import type { CommunitySpaceOut, ThreadOut, CommunityStatsOut } from "@/lib/api/hooks/community";
import type { AgentProfileOut } from "@/lib/api/hooks/marketplace";

// ---------------------------------------------------------------------------
// Community mock data
// ---------------------------------------------------------------------------

export const MOCK_COMMUNITY_SPACES: CommunitySpaceOut[] = [
  {
    id: "sp-1",
    slug: "visa-experiences",
    name: "Visa Experiences",
    description: "Share your visa application journey — timelines, tips, and lessons learned from real applicants.",
    icon: "✈️",
    member_count: 1243,
    thread_count: 328,
    created_at: "2025-11-01T00:00:00Z",
  },
  {
    id: "sp-2",
    slug: "skilled-worker-visas",
    name: "Skilled Worker Visas",
    description: "Discussion hub for subclass 189, 190, 491, 482, and employer-sponsored pathways.",
    icon: "💼",
    member_count: 987,
    thread_count: 256,
    created_at: "2025-11-01T00:00:00Z",
  },
  {
    id: "sp-3",
    slug: "partner-family-visas",
    name: "Partner & Family Visas",
    description: "Support and advice for partner (820/801), parent (143), and other family-stream visas.",
    icon: "❤️",
    member_count: 764,
    thread_count: 189,
    created_at: "2025-11-01T00:00:00Z",
  },
  {
    id: "sp-4",
    slug: "student-graduate-visas",
    name: "Student & Graduate Visas",
    description: "Everything about student visa (500), graduate visa (485), and transitioning to PR.",
    icon: "🎓",
    member_count: 1102,
    thread_count: 412,
    created_at: "2025-11-01T00:00:00Z",
  },
  {
    id: "sp-5",
    slug: "settlement-life",
    name: "Settlement & Life in Australia",
    description: "Tips on housing, banking, healthcare, schools, and settling into Australian life.",
    icon: "🏡",
    member_count: 892,
    thread_count: 201,
    created_at: "2025-11-15T00:00:00Z",
  },
  {
    id: "sp-6",
    slug: "document-help",
    name: "Document Help",
    description: "Questions about police checks, health exams, skills assessments, English tests, and more.",
    icon: "📄",
    member_count: 654,
    thread_count: 178,
    created_at: "2025-12-01T00:00:00Z",
  },
];

export const MOCK_COMMUNITY_STATS: CommunityStatsOut = {
  total_spaces: 6,
  total_threads: 1564,
  total_comments: 8721,
};

export const MOCK_RECENT_THREADS: ThreadOut[] = [
  {
    id: "th-1",
    space_id: "sp-1",
    space_slug: "visa-experiences",
    space_name: "Visa Experiences",
    author_display_name: "MelbMigrant",
    is_anonymous: false,
    title: "189 visa granted after 14 months — full timeline inside",
    body: "Just got the golden email! Here's my complete timeline from EOI to grant. Happy to answer questions.",
    upvotes: 47,
    reply_count: 23,
    view_count: 1892,
    is_pinned: false,
    status: "active",
    created_at: "2026-04-14T09:30:00Z",
    updated_at: "2026-04-14T09:30:00Z",
  },
  {
    id: "th-2",
    space_id: "sp-2",
    space_slug: "skilled-worker-visas",
    space_name: "Skilled Worker Visas",
    author_display_name: null,
    is_anonymous: true,
    title: "482 to 186 transition — employer not cooperating, what are my options?",
    body: "I've been on a 482 for 2 years and my employer is now reluctant to sponsor my 186. Has anyone dealt with this?",
    upvotes: 31,
    reply_count: 18,
    view_count: 943,
    is_pinned: false,
    status: "active",
    created_at: "2026-04-13T15:20:00Z",
    updated_at: "2026-04-13T15:20:00Z",
  },
  {
    id: "th-3",
    space_id: "sp-3",
    space_slug: "partner-family-visas",
    space_name: "Partner & Family Visas",
    author_display_name: "SydneyLove",
    is_anonymous: false,
    title: "Partner visa 820 processing time — applied Jan 2026",
    body: "Filed my 820 partner visa in January 2026. Anyone else in the same boat? Curious about current processing times.",
    upvotes: 19,
    reply_count: 14,
    view_count: 672,
    is_pinned: false,
    status: "active",
    created_at: "2026-04-12T11:00:00Z",
    updated_at: "2026-04-12T11:00:00Z",
  },
  {
    id: "th-4",
    space_id: "sp-4",
    space_slug: "student-graduate-visas",
    space_name: "Student & Graduate Visas",
    author_display_name: "UniGrad2026",
    is_anonymous: false,
    title: "485 visa changes July 2026 — what we know so far",
    body: "Compiling all the confirmed and rumoured changes to the 485 post-study work visa. Will keep this updated.",
    upvotes: 56,
    reply_count: 31,
    view_count: 2341,
    is_pinned: true,
    status: "active",
    created_at: "2026-04-11T08:45:00Z",
    updated_at: "2026-04-15T10:00:00Z",
  },
  {
    id: "th-5",
    space_id: "sp-5",
    space_slug: "settlement-life",
    space_name: "Settlement & Life in Australia",
    author_display_name: null,
    is_anonymous: true,
    title: "Best suburbs in Melbourne for new migrants on a budget?",
    body: "Moving to Melbourne next month with my family. Looking for affordable suburbs with good schools and public transport.",
    upvotes: 24,
    reply_count: 19,
    view_count: 1105,
    is_pinned: false,
    status: "active",
    created_at: "2026-04-10T14:30:00Z",
    updated_at: "2026-04-10T14:30:00Z",
  },
  {
    id: "th-6",
    space_id: "sp-6",
    space_slug: "document-help",
    space_name: "Document Help",
    author_display_name: "DocCheck",
    is_anonymous: false,
    title: "PTE vs IELTS for 190 visa — which is easier to score 79+?",
    body: "Need Superior English for my 190 nomination. Has anyone tried both tests? Which one did you find easier?",
    upvotes: 38,
    reply_count: 27,
    view_count: 1567,
    is_pinned: false,
    status: "active",
    created_at: "2026-04-09T10:15:00Z",
    updated_at: "2026-04-09T10:15:00Z",
  },
  {
    id: "th-7",
    space_id: "sp-2",
    space_slug: "skilled-worker-visas",
    space_name: "Skilled Worker Visas",
    author_display_name: "TechWorkerAU",
    is_anonymous: false,
    title: "Software engineer 189 EOI — 85 points, how long to expect?",
    body: "Submitted my EOI with 85 points under 261313. Current rounds seem to need 90+. Should I look at 190 instead?",
    upvotes: 22,
    reply_count: 15,
    view_count: 834,
    is_pinned: false,
    status: "active",
    created_at: "2026-04-08T16:00:00Z",
    updated_at: "2026-04-08T16:00:00Z",
  },
  {
    id: "th-8",
    space_id: "sp-1",
    space_slug: "visa-experiences",
    space_name: "Visa Experiences",
    author_display_name: null,
    is_anonymous: true,
    title: "Bridging visa A expired while waiting for AAT — help!",
    body: "My BVA lapsed and I didn't realise. Now I'm on no visa. What should I do? Is there any way to fix this?",
    upvotes: 15,
    reply_count: 11,
    view_count: 523,
    is_pinned: false,
    status: "active",
    created_at: "2026-04-07T09:00:00Z",
    updated_at: "2026-04-07T09:00:00Z",
  },
];

// ---------------------------------------------------------------------------
// Marketplace / Consultants mock data
// ---------------------------------------------------------------------------

export const MOCK_AGENTS: AgentProfileOut[] = [
  {
    id: "ag-1",
    user_id: "u-1",
    listing_type: "individual",
    firm_name: null,
    omara_number: "1280456",
    bio: "Over 15 years of experience helping skilled workers and families navigate the Australian immigration system. Specialising in employer-sponsored and skilled independent visas.",
    website: "https://example.com",
    phone: "+61 2 9000 1234",
    role: "Registered Migration Agent",
    city: "Sydney",
    state: "NSW",
    specializations: ["Skilled Worker (482)", "Employer Sponsored (186)", "Skilled Independent (189)"],
    languages: ["English", "Mandarin"],
    years_experience: 15,
    consultation_fee: 350,
    response_time_hours: 4,
    tier: "highly_recommended",
    status: "approved",
    featured: true,
    avatar_color: "#7A5AF8",
    rating: 4.9,
    review_count: 127,
    submitted_at: "2025-10-01T00:00:00Z",
    approved_at: "2025-10-02T00:00:00Z",
    created_at: "2025-10-01T00:00:00Z",
    updated_at: "2026-03-15T00:00:00Z",
    display_name: "Sarah Chen",
    email: "sarah.chen@example.com",
  },
  {
    id: "ag-2",
    user_id: "u-2",
    listing_type: "company",
    firm_name: "Melbourne Migration Partners",
    omara_number: "1375821",
    bio: "Boutique migration firm with a team of 6 agents covering all visa subclasses. We pride ourselves on transparent communication and high grant rates.",
    website: "https://example.com",
    phone: "+61 3 9000 5678",
    role: "Principal Agent",
    city: "Melbourne",
    state: "VIC",
    specializations: ["Partner Visa (820/801)", "Parent Visa (143)", "Student Visa (500)"],
    languages: ["English", "Hindi", "Punjabi"],
    years_experience: 12,
    consultation_fee: 300,
    response_time_hours: 6,
    tier: "highly_recommended",
    status: "approved",
    featured: true,
    avatar_color: "#1B7B6F",
    rating: 4.8,
    review_count: 94,
    submitted_at: "2025-10-05T00:00:00Z",
    approved_at: "2025-10-06T00:00:00Z",
    created_at: "2025-10-05T00:00:00Z",
    updated_at: "2026-02-20T00:00:00Z",
    display_name: "Rajesh Patel",
    email: "rajesh@mmp.example.com",
  },
  {
    id: "ag-3",
    user_id: "u-3",
    listing_type: "individual",
    firm_name: null,
    omara_number: "1492037",
    bio: "Passionate about helping international students transition to permanent residency. I've personally been through the 500 → 485 → 189 pathway and understand the journey.",
    website: null,
    phone: "+61 7 3000 9012",
    role: "Migration Agent",
    city: "Brisbane",
    state: "QLD",
    specializations: ["Student Visa (500)", "Graduate Visa (485)", "Skilled Nominated (190)"],
    languages: ["English", "Korean"],
    years_experience: 6,
    consultation_fee: 200,
    response_time_hours: 2,
    tier: "recommended",
    status: "approved",
    featured: false,
    avatar_color: "#E04F5F",
    rating: 4.7,
    review_count: 53,
    submitted_at: "2025-11-10T00:00:00Z",
    approved_at: "2025-11-12T00:00:00Z",
    created_at: "2025-11-10T00:00:00Z",
    updated_at: "2026-01-30T00:00:00Z",
    display_name: "Ji-Yeon Park",
    email: "jiyeon@example.com",
  },
  {
    id: "ag-4",
    user_id: "u-4",
    listing_type: "company",
    firm_name: "WA Visa Solutions",
    omara_number: "1187654",
    bio: "Perth-based firm specialising in business and investor visas. We help entrepreneurs and business owners establish themselves in Western Australia.",
    website: "https://example.com",
    phone: "+61 8 6000 3456",
    role: "Senior Migration Agent",
    city: "Perth",
    state: "WA",
    specializations: ["Business Innovation (188)", "Employer Sponsored (186)", "Regional (491)"],
    languages: ["English", "Arabic", "Urdu"],
    years_experience: 20,
    consultation_fee: 400,
    response_time_hours: 8,
    tier: "highly_recommended",
    status: "approved",
    featured: true,
    avatar_color: "#D97706",
    rating: 4.9,
    review_count: 156,
    submitted_at: "2025-09-20T00:00:00Z",
    approved_at: "2025-09-21T00:00:00Z",
    created_at: "2025-09-20T00:00:00Z",
    updated_at: "2026-04-01T00:00:00Z",
    display_name: "Omar Khalid",
    email: "omar@wavisas.example.com",
  },
  {
    id: "ag-5",
    user_id: "u-5",
    listing_type: "individual",
    firm_name: null,
    omara_number: "1563210",
    bio: "Former Department of Home Affairs officer turned migration agent. My insider knowledge helps clients prepare stronger applications with fewer delays.",
    website: "https://example.com",
    phone: "+61 2 9000 7890",
    role: "Registered Migration Agent",
    city: "Sydney",
    state: "NSW",
    specializations: ["Skilled Independent (189)", "Skilled Nominated (190)", "Partner Visa (820/801)"],
    languages: ["English", "Vietnamese", "Cantonese"],
    years_experience: 10,
    consultation_fee: 320,
    response_time_hours: 3,
    tier: "recommended",
    status: "approved",
    featured: false,
    avatar_color: "#2563EB",
    rating: 4.6,
    review_count: 71,
    submitted_at: "2025-12-01T00:00:00Z",
    approved_at: "2025-12-03T00:00:00Z",
    created_at: "2025-12-01T00:00:00Z",
    updated_at: "2026-03-10T00:00:00Z",
    display_name: "Linh Nguyen",
    email: "linh@example.com",
  },
  {
    id: "ag-6",
    user_id: "u-6",
    listing_type: "individual",
    firm_name: null,
    omara_number: "1421098",
    bio: "Adelaide-based agent focusing on regional visas and state nomination. I help clients leverage South Australia's favourable nomination criteria.",
    website: null,
    phone: "+61 8 7000 1234",
    role: "Migration Agent",
    city: "Adelaide",
    state: "SA",
    specializations: ["Regional (491)", "Skilled Nominated (190)", "Graduate Visa (485)"],
    languages: ["English", "Tamil", "Hindi"],
    years_experience: 8,
    consultation_fee: 250,
    response_time_hours: 5,
    tier: "verified",
    status: "approved",
    featured: false,
    avatar_color: "#059669",
    rating: 4.5,
    review_count: 38,
    submitted_at: "2026-01-15T00:00:00Z",
    approved_at: "2026-01-17T00:00:00Z",
    created_at: "2026-01-15T00:00:00Z",
    updated_at: "2026-04-05T00:00:00Z",
    display_name: "Priya Sundaram",
    email: "priya@example.com",
  },
  {
    id: "ag-7",
    user_id: "u-7",
    listing_type: "company",
    firm_name: "Canberra Immigration Group",
    omara_number: "1298765",
    bio: "Full-service migration firm in the capital. Direct liaison with the Department of Home Affairs. We handle complex and refused cases.",
    website: "https://example.com",
    phone: "+61 2 6000 5678",
    role: "Principal Agent",
    city: "Canberra",
    state: "ACT",
    specializations: ["Skilled Worker (482)", "Employer Sponsored (186)", "Business Innovation (188)"],
    languages: ["English", "Tagalog", "Japanese"],
    years_experience: 18,
    consultation_fee: 380,
    response_time_hours: 4,
    tier: "highly_recommended",
    status: "approved",
    featured: false,
    avatar_color: "#7C3AED",
    rating: 4.8,
    review_count: 112,
    submitted_at: "2025-10-10T00:00:00Z",
    approved_at: "2025-10-11T00:00:00Z",
    created_at: "2025-10-10T00:00:00Z",
    updated_at: "2026-03-25T00:00:00Z",
    display_name: "Marcus Reyes",
    email: "marcus@cig.example.com",
  },
  {
    id: "ag-8",
    user_id: "u-8",
    listing_type: "individual",
    firm_name: null,
    omara_number: "1634521",
    bio: "Specialist in partner and family visas. I understand the emotional side of immigration and provide compassionate, thorough guidance through the process.",
    website: null,
    phone: "+61 3 9000 2345",
    role: "Migration Agent",
    city: "Melbourne",
    state: "VIC",
    specializations: ["Partner Visa (820/801)", "Parent Visa (143)", "Skilled Worker (482)"],
    languages: ["English", "Spanish", "Thai"],
    years_experience: 9,
    consultation_fee: 280,
    response_time_hours: 3,
    tier: "recommended",
    status: "approved",
    featured: false,
    avatar_color: "#EC4899",
    rating: 4.7,
    review_count: 64,
    submitted_at: "2026-02-01T00:00:00Z",
    approved_at: "2026-02-03T00:00:00Z",
    created_at: "2026-02-01T00:00:00Z",
    updated_at: "2026-04-10T00:00:00Z",
    display_name: "Isabella Torres",
    email: "isabella@example.com",
  },
];
