// Mock data for the (currently hidden) consultant directory only.
// Community data is never mocked — it comes live from the backend.

import type { AgentProfileOut } from "@/lib/api/hooks/marketplace";

// ---------------------------------------------------------------------------
// Marketplace / Consultants mock data
// ---------------------------------------------------------------------------

export const MOCK_AGENTS: AgentProfileOut[] = [
  {
    id: "ag-1",
    user_id: "u-1",
    listing_type: "individual",
    firm_name: null,
    omara_number: "1280456",
    bio: "Over 15 years of experience helping skilled workers and families navigate the Australian immigration system. Specialising in employer-sponsored and skilled independent visas.",
    website: "https://example.com",
    phone: "+61 2 9000 1234",
    role: "Registered Migration Agent",
    city: "Sydney",
    state: "NSW",
    specializations: ["Skilled Worker (482)", "Employer Sponsored (186)", "Skilled Independent (189)"],
    languages: ["English", "Mandarin"],
    years_experience: 15,
    consultation_fee: 350,
    response_time_hours: 4,
    tier: "highly_recommended",
    status: "approved",
    featured: true,
    avatar_color: "#7A5AF8",
    rating: 4.9,
    review_count: 127,
    submitted_at: "2025-10-01T00:00:00Z",
    approved_at: "2025-10-02T00:00:00Z",
    created_at: "2025-10-01T00:00:00Z",
    updated_at: "2026-03-15T00:00:00Z",
    display_name: "Sarah Chen",
    email: "sarah.chen@example.com",
  },
  {
    id: "ag-2",
    user_id: "u-2",
    listing_type: "company",
    firm_name: "Melbourne Migration Partners",
    omara_number: "1375821",
    bio: "Boutique migration firm with a team of 6 agents covering all visa subclasses. We pride ourselves on transparent communication and high grant rates.",
    website: "https://example.com",
    phone: "+61 3 9000 5678",
    role: "Principal Agent",
    city: "Melbourne",
    state: "VIC",
    specializations: ["Partner Visa (820/801)", "Parent Visa (143)", "Student Visa (500)"],
    languages: ["English", "Hindi", "Punjabi"],
    years_experience: 12,
    consultation_fee: 300,
    response_time_hours: 6,
    tier: "highly_recommended",
    status: "approved",
    featured: true,
    avatar_color: "#1B7B6F",
    rating: 4.8,
    review_count: 94,
    submitted_at: "2025-10-05T00:00:00Z",
    approved_at: "2025-10-06T00:00:00Z",
    created_at: "2025-10-05T00:00:00Z",
    updated_at: "2026-02-20T00:00:00Z",
    display_name: "Rajesh Patel",
    email: "rajesh@mmp.example.com",
  },
  {
    id: "ag-3",
    user_id: "u-3",
    listing_type: "individual",
    firm_name: null,
    omara_number: "1492037",
    bio: "Passionate about helping international students transition to permanent residency. I've personally been through the 500 → 485 → 189 pathway and understand the journey.",
    website: null,
    phone: "+61 7 3000 9012",
    role: "Migration Agent",
    city: "Brisbane",
    state: "QLD",
    specializations: ["Student Visa (500)", "Graduate Visa (485)", "Skilled Nominated (190)"],
    languages: ["English", "Korean"],
    years_experience: 6,
    consultation_fee: 200,
    response_time_hours: 2,
    tier: "recommended",
    status: "approved",
    featured: false,
    avatar_color: "#E04F5F",
    rating: 4.7,
    review_count: 53,
    submitted_at: "2025-11-10T00:00:00Z",
    approved_at: "2025-11-12T00:00:00Z",
    created_at: "2025-11-10T00:00:00Z",
    updated_at: "2026-01-30T00:00:00Z",
    display_name: "Ji-Yeon Park",
    email: "jiyeon@example.com",
  },
  {
    id: "ag-4",
    user_id: "u-4",
    listing_type: "company",
    firm_name: "WA Visa Solutions",
    omara_number: "1187654",
    bio: "Perth-based firm specialising in business and investor visas. We help entrepreneurs and business owners establish themselves in Western Australia.",
    website: "https://example.com",
    phone: "+61 8 6000 3456",
    role: "Senior Migration Agent",
    city: "Perth",
    state: "WA",
    specializations: ["Business Innovation (188)", "Employer Sponsored (186)", "Regional (491)"],
    languages: ["English", "Arabic", "Urdu"],
    years_experience: 20,
    consultation_fee: 400,
    response_time_hours: 8,
    tier: "highly_recommended",
    status: "approved",
    featured: true,
    avatar_color: "#D97706",
    rating: 4.9,
    review_count: 156,
    submitted_at: "2025-09-20T00:00:00Z",
    approved_at: "2025-09-21T00:00:00Z",
    created_at: "2025-09-20T00:00:00Z",
    updated_at: "2026-04-01T00:00:00Z",
    display_name: "Omar Khalid",
    email: "omar@wavisas.example.com",
  },
  {
    id: "ag-5",
    user_id: "u-5",
    listing_type: "individual",
    firm_name: null,
    omara_number: "1563210",
    bio: "Former Department of Home Affairs officer turned migration agent. My insider knowledge helps clients prepare stronger applications with fewer delays.",
    website: "https://example.com",
    phone: "+61 2 9000 7890",
    role: "Registered Migration Agent",
    city: "Sydney",
    state: "NSW",
    specializations: ["Skilled Independent (189)", "Skilled Nominated (190)", "Partner Visa (820/801)"],
    languages: ["English", "Vietnamese", "Cantonese"],
    years_experience: 10,
    consultation_fee: 320,
    response_time_hours: 3,
    tier: "recommended",
    status: "approved",
    featured: false,
    avatar_color: "#2563EB",
    rating: 4.6,
    review_count: 71,
    submitted_at: "2025-12-01T00:00:00Z",
    approved_at: "2025-12-03T00:00:00Z",
    created_at: "2025-12-01T00:00:00Z",
    updated_at: "2026-03-10T00:00:00Z",
    display_name: "Linh Nguyen",
    email: "linh@example.com",
  },
  {
    id: "ag-6",
    user_id: "u-6",
    listing_type: "individual",
    firm_name: null,
    omara_number: "1421098",
    bio: "Adelaide-based agent focusing on regional visas and state nomination. I help clients leverage South Australia's favourable nomination criteria.",
    website: null,
    phone: "+61 8 7000 1234",
    role: "Migration Agent",
    city: "Adelaide",
    state: "SA",
    specializations: ["Regional (491)", "Skilled Nominated (190)", "Graduate Visa (485)"],
    languages: ["English", "Tamil", "Hindi"],
    years_experience: 8,
    consultation_fee: 250,
    response_time_hours: 5,
    tier: "verified",
    status: "approved",
    featured: false,
    avatar_color: "#059669",
    rating: 4.5,
    review_count: 38,
    submitted_at: "2026-01-15T00:00:00Z",
    approved_at: "2026-01-17T00:00:00Z",
    created_at: "2026-01-15T00:00:00Z",
    updated_at: "2026-04-05T00:00:00Z",
    display_name: "Priya Sundaram",
    email: "priya@example.com",
  },
  {
    id: "ag-7",
    user_id: "u-7",
    listing_type: "company",
    firm_name: "Canberra Immigration Group",
    omara_number: "1298765",
    bio: "Full-service migration firm in the capital. Direct liaison with the Department of Home Affairs. We handle complex and refused cases.",
    website: "https://example.com",
    phone: "+61 2 6000 5678",
    role: "Principal Agent",
    city: "Canberra",
    state: "ACT",
    specializations: ["Skilled Worker (482)", "Employer Sponsored (186)", "Business Innovation (188)"],
    languages: ["English", "Tagalog", "Japanese"],
    years_experience: 18,
    consultation_fee: 380,
    response_time_hours: 4,
    tier: "highly_recommended",
    status: "approved",
    featured: false,
    avatar_color: "#7C3AED",
    rating: 4.8,
    review_count: 112,
    submitted_at: "2025-10-10T00:00:00Z",
    approved_at: "2025-10-11T00:00:00Z",
    created_at: "2025-10-10T00:00:00Z",
    updated_at: "2026-03-25T00:00:00Z",
    display_name: "Marcus Reyes",
    email: "marcus@cig.example.com",
  },
  {
    id: "ag-8",
    user_id: "u-8",
    listing_type: "individual",
    firm_name: null,
    omara_number: "1634521",
    bio: "Specialist in partner and family visas. I understand the emotional side of immigration and provide compassionate, thorough guidance through the process.",
    website: null,
    phone: "+61 3 9000 2345",
    role: "Migration Agent",
    city: "Melbourne",
    state: "VIC",
    specializations: ["Partner Visa (820/801)", "Parent Visa (143)", "Skilled Worker (482)"],
    languages: ["English", "Spanish", "Thai"],
    years_experience: 9,
    consultation_fee: 280,
    response_time_hours: 3,
    tier: "recommended",
    status: "approved",
    featured: false,
    avatar_color: "#EC4899",
    rating: 4.7,
    review_count: 64,
    submitted_at: "2026-02-01T00:00:00Z",
    approved_at: "2026-02-03T00:00:00Z",
    created_at: "2026-02-01T00:00:00Z",
    updated_at: "2026-04-10T00:00:00Z",
    display_name: "Isabella Torres",
    email: "isabella@example.com",
  },
];
