import type { City, VisaType, Language } from "./constants";

export interface Consultant {
  id: string;
  name: string;
  initials: string;
  firm: string;
  role: string;
  city: City;
  state: string;
  specializations: VisaType[];
  languages: Language[];
  yearsExperience: number;
  rating: number;
  reviewCount: number;
  isOMARAVerified: boolean;
  isFeatured: boolean;
  marnNumber: string;
  bio: string;
  consultationFee: string;
  responseTime: string;
  avatarColor: string;
}

const AVATAR_COLORS = [
  "bg-purple/10 text-purple",
  "bg-teal/10 text-teal",
  "bg-navy/10 text-navy",
  "bg-purple-muted/30 text-purple-deep",
  "bg-teal-light/20 text-teal",
];

export const consultants: Consultant[] = [
  // ── Sydney (6) ──
  {
    id: "syd-1",
    name: "Sarah Mitchell",
    initials: "SM",
    firm: "Harbour City Immigration",
    role: "Principal Agent",
    city: "Sydney",
    state: "NSW",
    specializations: ["Skilled Independent (189)", "Skilled Nominated (190)", "Employer Sponsored (186)"],
    languages: ["English"],
    yearsExperience: 18,
    rating: 4.9,
    reviewCount: 127,
    isOMARAVerified: true,
    isFeatured: true,
    marnNumber: "MARN 0741256",
    bio: "Specialist in skilled migration pathways with 18 years of experience navigating complex points-based applications.",
    consultationFee: "From $300",
    responseTime: "Within 24h",
    avatarColor: AVATAR_COLORS[0],
  },
  {
    id: "syd-2",
    name: "Wei Chen",
    initials: "WC",
    firm: "Pacific Migration Group",
    role: "Senior Consultant",
    city: "Sydney",
    state: "NSW",
    specializations: ["Business Innovation (188)", "Skilled Worker (482)", "Employer Sponsored (186)"],
    languages: ["English", "Mandarin", "Cantonese"],
    yearsExperience: 12,
    rating: 4.8,
    reviewCount: 89,
    isOMARAVerified: true,
    isFeatured: true,
    marnNumber: "MARN 0852374",
    bio: "Bilingual consultant helping business investors and skilled workers establish their future in Australia.",
    consultationFee: "From $250",
    responseTime: "Same day",
    avatarColor: AVATAR_COLORS[1],
  },
  {
    id: "syd-3",
    name: "Priya Sharma",
    initials: "PS",
    firm: "Southern Cross Visa Services",
    role: "Migration Lawyer",
    city: "Sydney",
    state: "NSW",
    specializations: ["Partner Visa (820/801)", "Parent Visa (143)", "Student Visa (500)"],
    languages: ["English", "Hindi", "Punjabi"],
    yearsExperience: 9,
    rating: 4.7,
    reviewCount: 64,
    isOMARAVerified: true,
    isFeatured: false,
    marnNumber: "MARN 0963481",
    bio: "Family migration specialist with a compassionate approach to partner and parent visa applications.",
    consultationFee: "Free Initial",
    responseTime: "Within 24h",
    avatarColor: AVATAR_COLORS[2],
  },
  {
    id: "syd-4",
    name: "James O'Brien",
    initials: "JO",
    firm: "O'Brien Migration Law",
    role: "Principal Agent",
    city: "Sydney",
    state: "NSW",
    specializations: ["Skilled Worker (482)", "Employer Sponsored (186)", "Regional (491)"],
    languages: ["English"],
    yearsExperience: 22,
    rating: 4.9,
    reviewCount: 143,
    isOMARAVerified: true,
    isFeatured: false,
    marnNumber: "MARN 0634129",
    bio: "Veteran migration agent specialising in employer-sponsored pathways and regional visa strategies.",
    consultationFee: "From $350",
    responseTime: "Within 2h",
    avatarColor: AVATAR_COLORS[3],
  },
  {
    id: "syd-5",
    name: "Fatima Al-Rashid",
    initials: "FA",
    firm: "Bridgeway Immigration",
    role: "Registered Agent",
    city: "Sydney",
    state: "NSW",
    specializations: ["Partner Visa (820/801)", "Student Visa (500)", "Graduate Visa (485)"],
    languages: ["English", "Arabic"],
    yearsExperience: 6,
    rating: 4.6,
    reviewCount: 38,
    isOMARAVerified: true,
    isFeatured: false,
    marnNumber: "MARN 1074562",
    bio: "Helping Arabic-speaking families navigate the Australian visa system with clarity and care.",
    consultationFee: "From $200",
    responseTime: "Within 24h",
    avatarColor: AVATAR_COLORS[4],
  },
  {
    id: "syd-6",
    name: "David Park",
    initials: "DP",
    firm: "Asia Pacific Visas",
    role: "Senior Consultant",
    city: "Sydney",
    state: "NSW",
    specializations: ["Student Visa (500)", "Graduate Visa (485)", "Skilled Independent (189)"],
    languages: ["English", "Korean"],
    yearsExperience: 8,
    rating: 4.7,
    reviewCount: 52,
    isOMARAVerified: true,
    isFeatured: false,
    marnNumber: "MARN 0985673",
    bio: "Student visa expert helping international graduates transition to skilled migration pathways.",
    consultationFee: "From $200",
    responseTime: "Same day",
    avatarColor: AVATAR_COLORS[0],
  },

  // ── Melbourne (6) ──
  {
    id: "mel-1",
    name: "Rajesh Patel",
    initials: "RP",
    firm: "Melbourne Migration Centre",
    role: "Principal Agent",
    city: "Melbourne",
    state: "VIC",
    specializations: ["Skilled Independent (189)", "Skilled Nominated (190)", "Skilled Worker (482)"],
    languages: ["English", "Hindi", "Tamil"],
    yearsExperience: 15,
    rating: 4.8,
    reviewCount: 112,
    isOMARAVerified: true,
    isFeatured: true,
    marnNumber: "MARN 0756893",
    bio: "Leading skilled migration consultant in Melbourne with expertise across all points-based visa subclasses.",
    consultationFee: "From $280",
    responseTime: "Within 24h",
    avatarColor: AVATAR_COLORS[1],
  },
  {
    id: "mel-2",
    name: "Emma Thompson",
    initials: "ET",
    firm: "Yarra Valley Visas",
    role: "Migration Lawyer",
    city: "Melbourne",
    state: "VIC",
    specializations: ["Partner Visa (820/801)", "Parent Visa (143)"],
    languages: ["English"],
    yearsExperience: 14,
    rating: 4.9,
    reviewCount: 98,
    isOMARAVerified: true,
    isFeatured: true,
    marnNumber: "MARN 0768234",
    bio: "Family visa specialist known for high success rates in complex partner and parent visa matters.",
    consultationFee: "From $320",
    responseTime: "Within 2h",
    avatarColor: AVATAR_COLORS[2],
  },
  {
    id: "mel-3",
    name: "Tran Nguyen",
    initials: "TN",
    firm: "Viet-Oz Migration",
    role: "Senior Consultant",
    city: "Melbourne",
    state: "VIC",
    specializations: ["Student Visa (500)", "Graduate Visa (485)", "Skilled Worker (482)"],
    languages: ["English", "Vietnamese"],
    yearsExperience: 7,
    rating: 4.6,
    reviewCount: 41,
    isOMARAVerified: true,
    isFeatured: false,
    marnNumber: "MARN 1023467",
    bio: "Helping Vietnamese students and graduates build their careers in Australia through the right visa pathway.",
    consultationFee: "From $180",
    responseTime: "Same day",
    avatarColor: AVATAR_COLORS[3],
  },
  {
    id: "mel-4",
    name: "Michael Kouris",
    initials: "MK",
    firm: "Kouris & Associates",
    role: "Principal Agent",
    city: "Melbourne",
    state: "VIC",
    specializations: ["Employer Sponsored (186)", "Business Innovation (188)", "Skilled Worker (482)"],
    languages: ["English"],
    yearsExperience: 20,
    rating: 4.8,
    reviewCount: 136,
    isOMARAVerified: true,
    isFeatured: false,
    marnNumber: "MARN 0645782",
    bio: "Two decades of experience helping employers sponsor top international talent for Australian businesses.",
    consultationFee: "From $350",
    responseTime: "Within 24h",
    avatarColor: AVATAR_COLORS[4],
  },
  {
    id: "mel-5",
    name: "Ananya Desai",
    initials: "AD",
    firm: "First Step Migration",
    role: "Registered Agent",
    city: "Melbourne",
    state: "VIC",
    specializations: ["Skilled Independent (189)", "Regional (491)", "Graduate Visa (485)"],
    languages: ["English", "Hindi", "Urdu"],
    yearsExperience: 5,
    rating: 4.5,
    reviewCount: 29,
    isOMARAVerified: true,
    isFeatured: false,
    marnNumber: "MARN 1089456",
    bio: "Passionate about helping skilled migrants find the right pathway, including regional visa options.",
    consultationFee: "Free Initial",
    responseTime: "Within 24h",
    avatarColor: AVATAR_COLORS[0],
  },
  {
    id: "mel-6",
    name: "Liam Foster",
    initials: "LF",
    firm: "Foster Migration Lawyers",
    role: "Migration Lawyer",
    city: "Melbourne",
    state: "VIC",
    specializations: ["Partner Visa (820/801)", "Parent Visa (143)", "Student Visa (500)"],
    languages: ["English", "Spanish"],
    yearsExperience: 11,
    rating: 4.7,
    reviewCount: 73,
    isOMARAVerified: true,
    isFeatured: false,
    marnNumber: "MARN 0876542",
    bio: "Family and student visa law specialist with a focus on complex character and health waiver cases.",
    consultationFee: "From $300",
    responseTime: "Within 24h",
    avatarColor: AVATAR_COLORS[1],
  },

  // ── Brisbane (4) ──
  {
    id: "bri-1",
    name: "Sophie Williams",
    initials: "SW",
    firm: "Queensland Migration Services",
    role: "Principal Agent",
    city: "Brisbane",
    state: "QLD",
    specializations: ["Skilled Nominated (190)", "Regional (491)", "Employer Sponsored (186)"],
    languages: ["English"],
    yearsExperience: 16,
    rating: 4.8,
    reviewCount: 94,
    isOMARAVerified: true,
    isFeatured: false,
    marnNumber: "MARN 0748921",
    bio: "Queensland's leading regional visa expert helping skilled workers settle in regional Australia.",
    consultationFee: "From $260",
    responseTime: "Within 24h",
    avatarColor: AVATAR_COLORS[2],
  },
  {
    id: "bri-2",
    name: "Amit Kumar",
    initials: "AK",
    firm: "Sunshine Migration",
    role: "Senior Consultant",
    city: "Brisbane",
    state: "QLD",
    specializations: ["Student Visa (500)", "Skilled Worker (482)", "Graduate Visa (485)"],
    languages: ["English", "Hindi", "Nepali"],
    yearsExperience: 8,
    rating: 4.6,
    reviewCount: 47,
    isOMARAVerified: true,
    isFeatured: false,
    marnNumber: "MARN 0978345",
    bio: "Guiding students and skilled workers through every step of the Australian visa process.",
    consultationFee: "From $200",
    responseTime: "Same day",
    avatarColor: AVATAR_COLORS[3],
  },
  {
    id: "bri-3",
    name: "Maria Santos",
    initials: "MS",
    firm: "Santos Visa Consulting",
    role: "Registered Agent",
    city: "Brisbane",
    state: "QLD",
    specializations: ["Partner Visa (820/801)", "Parent Visa (143)"],
    languages: ["English", "Tagalog", "Spanish"],
    yearsExperience: 6,
    rating: 4.5,
    reviewCount: 33,
    isOMARAVerified: true,
    isFeatured: false,
    marnNumber: "MARN 1056789",
    bio: "Filipino-Australian consultant specialising in family reunion visas and partner applications.",
    consultationFee: "Free Initial",
    responseTime: "Within 24h",
    avatarColor: AVATAR_COLORS[4],
  },
  {
    id: "bri-4",
    name: "Daniel Hughes",
    initials: "DH",
    firm: "River City Migration",
    role: "Senior Consultant",
    city: "Brisbane",
    state: "QLD",
    specializations: ["Business Innovation (188)", "Skilled Independent (189)", "Employer Sponsored (186)"],
    languages: ["English"],
    yearsExperience: 13,
    rating: 4.7,
    reviewCount: 68,
    isOMARAVerified: true,
    isFeatured: false,
    marnNumber: "MARN 0834567",
    bio: "Business and investor visa specialist helping entrepreneurs establish operations in Queensland.",
    consultationFee: "From $300",
    responseTime: "Within 24h",
    avatarColor: AVATAR_COLORS[0],
  },

  // ── Perth (3) ──
  {
    id: "per-1",
    name: "Aisha Khan",
    initials: "AK",
    firm: "Westcoast Immigration",
    role: "Principal Agent",
    city: "Perth",
    state: "WA",
    specializations: ["Skilled Nominated (190)", "Regional (491)", "Skilled Independent (189)"],
    languages: ["English", "Urdu", "Arabic"],
    yearsExperience: 11,
    rating: 4.8,
    reviewCount: 76,
    isOMARAVerified: true,
    isFeatured: true,
    marnNumber: "MARN 0867432",
    bio: "Perth's trusted migration agent for skilled workers seeking State nomination and regional pathways.",
    consultationFee: "From $250",
    responseTime: "Within 2h",
    avatarColor: AVATAR_COLORS[1],
  },
  {
    id: "per-2",
    name: "Tom Henderson",
    initials: "TH",
    firm: "Henderson Migration",
    role: "Senior Consultant",
    city: "Perth",
    state: "WA",
    specializations: ["Employer Sponsored (186)", "Skilled Worker (482)"],
    languages: ["English"],
    yearsExperience: 19,
    rating: 4.7,
    reviewCount: 88,
    isOMARAVerified: true,
    isFeatured: false,
    marnNumber: "MARN 0678234",
    bio: "Specialising in employer-sponsored migration for Western Australia's mining and resources sector.",
    consultationFee: "From $300",
    responseTime: "Within 24h",
    avatarColor: AVATAR_COLORS[2],
  },
  {
    id: "per-3",
    name: "Suki Tanaka",
    initials: "ST",
    firm: "Perth Visa Hub",
    role: "Registered Agent",
    city: "Perth",
    state: "WA",
    specializations: ["Student Visa (500)", "Partner Visa (820/801)", "Graduate Visa (485)"],
    languages: ["English", "Japanese", "Thai"],
    yearsExperience: 5,
    rating: 4.5,
    reviewCount: 24,
    isOMARAVerified: true,
    isFeatured: false,
    marnNumber: "MARN 1098765",
    bio: "Multilingual agent helping international students and partners navigate their visa journey in Perth.",
    consultationFee: "From $180",
    responseTime: "Same day",
    avatarColor: AVATAR_COLORS[3],
  },

  // ── Adelaide (3) ──
  {
    id: "adl-1",
    name: "Chris Morgan",
    initials: "CM",
    firm: "Adelaide Migration Partners",
    role: "Principal Agent",
    city: "Adelaide",
    state: "SA",
    specializations: ["Regional (491)", "Skilled Nominated (190)", "Skilled Independent (189)"],
    languages: ["English"],
    yearsExperience: 14,
    rating: 4.8,
    reviewCount: 82,
    isOMARAVerified: true,
    isFeatured: false,
    marnNumber: "MARN 0789456",
    bio: "South Australia's regional migration expert with deep knowledge of state nomination pathways.",
    consultationFee: "From $250",
    responseTime: "Within 24h",
    avatarColor: AVATAR_COLORS[4],
  },
  {
    id: "adl-2",
    name: "Nisha Reddy",
    initials: "NR",
    firm: "Festival City Visas",
    role: "Senior Consultant",
    city: "Adelaide",
    state: "SA",
    specializations: ["Student Visa (500)", "Skilled Worker (482)", "Graduate Visa (485)"],
    languages: ["English", "Hindi", "Tamil"],
    yearsExperience: 7,
    rating: 4.6,
    reviewCount: 35,
    isOMARAVerified: true,
    isFeatured: false,
    marnNumber: "MARN 1012345",
    bio: "Student migration specialist helping international students build their future in South Australia.",
    consultationFee: "Free Initial",
    responseTime: "Same day",
    avatarColor: AVATAR_COLORS[0],
  },
  {
    id: "adl-3",
    name: "Oliver Schmidt",
    initials: "OS",
    firm: "Schmidt Immigration Law",
    role: "Migration Lawyer",
    city: "Adelaide",
    state: "SA",
    specializations: ["Partner Visa (820/801)", "Parent Visa (143)", "Business Innovation (188)"],
    languages: ["English"],
    yearsExperience: 10,
    rating: 4.7,
    reviewCount: 56,
    isOMARAVerified: true,
    isFeatured: false,
    marnNumber: "MARN 0912378",
    bio: "Migration lawyer specialising in family visas and business investor pathways to South Australia.",
    consultationFee: "From $280",
    responseTime: "Within 24h",
    avatarColor: AVATAR_COLORS[1],
  },

  // ── Canberra (2) ──
  {
    id: "can-1",
    name: "Angela Wu",
    initials: "AW",
    firm: "Capital Migration Advisory",
    role: "Senior Consultant",
    city: "Canberra",
    state: "ACT",
    specializations: ["Skilled Nominated (190)", "Skilled Independent (189)", "Employer Sponsored (186)"],
    languages: ["English", "Mandarin"],
    yearsExperience: 10,
    rating: 4.7,
    reviewCount: 58,
    isOMARAVerified: true,
    isFeatured: false,
    marnNumber: "MARN 0923456",
    bio: "ACT nomination specialist helping skilled migrants leverage Canberra's unique pathway options.",
    consultationFee: "From $250",
    responseTime: "Within 24h",
    avatarColor: AVATAR_COLORS[2],
  },
  {
    id: "can-2",
    name: "Robert Singh",
    initials: "RS",
    firm: "Parliament View Visas",
    role: "Registered Agent",
    city: "Canberra",
    state: "ACT",
    specializations: ["Student Visa (500)", "Graduate Visa (485)", "Regional (491)"],
    languages: ["English", "Punjabi", "Hindi"],
    yearsExperience: 4,
    rating: 4.4,
    reviewCount: 18,
    isOMARAVerified: true,
    isFeatured: false,
    marnNumber: "MARN 1123456",
    bio: "Young and driven agent supporting Canberra's growing international student community.",
    consultationFee: "Free Initial",
    responseTime: "Same day",
    avatarColor: AVATAR_COLORS[3],
  },

  // ── Hobart (2) ──
  {
    id: "hob-1",
    name: "Grace Taylor",
    initials: "GT",
    firm: "Tasmania Migration Services",
    role: "Principal Agent",
    city: "Hobart",
    state: "TAS",
    specializations: ["Regional (491)", "Skilled Nominated (190)", "Student Visa (500)"],
    languages: ["English"],
    yearsExperience: 12,
    rating: 4.8,
    reviewCount: 67,
    isOMARAVerified: true,
    isFeatured: false,
    marnNumber: "MARN 0845678",
    bio: "Tasmania's go-to migration agent for regional visa pathways and state nomination applications.",
    consultationFee: "From $230",
    responseTime: "Within 24h",
    avatarColor: AVATAR_COLORS[4],
  },
  {
    id: "hob-2",
    name: "Kiran Basnet",
    initials: "KB",
    firm: "Island Visa Consulting",
    role: "Registered Agent",
    city: "Hobart",
    state: "TAS",
    specializations: ["Student Visa (500)", "Graduate Visa (485)", "Skilled Worker (482)"],
    languages: ["English", "Nepali", "Hindi"],
    yearsExperience: 3,
    rating: 4.3,
    reviewCount: 12,
    isOMARAVerified: true,
    isFeatured: false,
    marnNumber: "MARN 1145678",
    bio: "Supporting Nepal's growing student community in Tasmania with visa guidance and support.",
    consultationFee: "From $150",
    responseTime: "Same day",
    avatarColor: AVATAR_COLORS[0],
  },

  // ── Darwin (1) ──
  {
    id: "dar-1",
    name: "Mark Johnson",
    initials: "MJ",
    firm: "Top End Migration",
    role: "Senior Consultant",
    city: "Darwin",
    state: "NT",
    specializations: ["Regional (491)", "Skilled Worker (482)", "Employer Sponsored (186)"],
    languages: ["English"],
    yearsExperience: 9,
    rating: 4.6,
    reviewCount: 31,
    isOMARAVerified: true,
    isFeatured: false,
    marnNumber: "MARN 0956789",
    bio: "Northern Territory specialist helping employers and skilled workers in Australia's Top End.",
    consultationFee: "From $220",
    responseTime: "Within 24h",
    avatarColor: AVATAR_COLORS[1],
  },
];
