import type {
  Client,
  Case,
  CaseDocument,
  DashboardStats,
  CaseActivityPoint,
  VisaBreakdownPoint,
  VisaSubclass,
  ActivityEntry,
  InboxEmail,
  ClientJourney,
  JourneyStep,
} from "@/lib/types/immigration";

// ── Helpers ──
function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

function hoursAgo(n: number): string {
  const d = new Date();
  d.setHours(d.getHours() - n);
  return d.toISOString();
}

// ── Visa Subclasses ──
export const visaSubclasses: VisaSubclass[] = [
  { code: "482", name: "Temporary Skill Shortage", category: "skilled" },
  { code: "186", name: "Employer Nomination Scheme", category: "skilled" },
  { code: "189", name: "Skilled Independent", category: "skilled" },
  { code: "190", name: "Skilled Nominated", category: "skilled" },
  { code: "491", name: "Skilled Work Regional", category: "skilled" },
  { code: "500", name: "Student Visa", category: "student" },
  { code: "820", name: "Partner (Temporary)", category: "family" },
  { code: "600", name: "Visitor Visa", category: "visitor" },
];

// ── Clients ──
export const mockClients: Client[] = [
  {
    id: "cl-001",
    first_name: "Priya",
    last_name: "Sharma",
    email: "priya.sharma@gmail.com",
    phone: "+61 412 345 678",
    nationality: "Indian",
    date_of_birth: "1992-03-15",
    passport_number: "K8472619",
    current_visa: "482",
    created_at: daysAgo(45),
    updated_at: daysAgo(1),
    cases_count: 2,
  },
  {
    id: "cl-002",
    first_name: "Wei",
    last_name: "Chen",
    email: "wei.chen@outlook.com",
    phone: "+61 423 456 789",
    nationality: "Chinese",
    date_of_birth: "1988-07-22",
    passport_number: "E38291047",
    current_visa: "500",
    created_at: daysAgo(30),
    updated_at: daysAgo(3),
    cases_count: 1,
  },
  {
    id: "cl-003",
    first_name: "James",
    last_name: "Thompson",
    email: "james.t@proton.me",
    phone: "+61 434 567 890",
    nationality: "British",
    date_of_birth: "1985-11-08",
    passport_number: "533847291",
    created_at: daysAgo(60),
    updated_at: daysAgo(5),
    cases_count: 1,
  },
  {
    id: "cl-004",
    first_name: "Maria",
    last_name: "Santos",
    email: "maria.santos@yahoo.com",
    phone: "+61 445 678 901",
    nationality: "Filipino",
    date_of_birth: "1995-01-20",
    passport_number: "P4829103",
    current_visa: "482",
    created_at: daysAgo(20),
    updated_at: hoursAgo(6),
    cases_count: 1,
  },
  {
    id: "cl-005",
    first_name: "Soo-jin",
    last_name: "Kim",
    email: "soojin.kim@gmail.com",
    phone: "+61 456 789 012",
    nationality: "Korean",
    date_of_birth: "1990-09-12",
    passport_number: "M72918304",
    created_at: daysAgo(15),
    updated_at: daysAgo(2),
    cases_count: 1,
  },
  {
    id: "cl-006",
    first_name: "Lucas",
    last_name: "Oliveira",
    email: "lucas.oliveira@hotmail.com",
    phone: "+61 467 890 123",
    nationality: "Brazilian",
    date_of_birth: "1993-06-30",
    passport_number: "FX482910",
    created_at: daysAgo(10),
    updated_at: hoursAgo(2),
    cases_count: 2,
  },
  {
    id: "cl-007",
    first_name: "Anika",
    last_name: "Patel",
    email: "anika.p@gmail.com",
    phone: "+61 478 901 234",
    nationality: "Indian",
    date_of_birth: "1997-04-18",
    passport_number: "K9182746",
    current_visa: "500",
    created_at: daysAgo(8),
    updated_at: hoursAgo(12),
    cases_count: 1,
  },
];

// ── Cases ──
export const mockCases: Case[] = [
  {
    id: "cs-001",
    client_id: "cl-001",
    client: mockClients[0],
    consultant_id: "con-001",
    visa_subclass: "186",
    visa_name: "Employer Nomination Scheme",
    stage: "documents_reviewing",
    priority: "high",
    created_at: daysAgo(40),
    updated_at: hoursAgo(3),
    notes_count: 8,
    documents_count: 12,
    documents_pending: 2,
    checklist_progress: 75,
  },
  {
    id: "cs-002",
    client_id: "cl-001",
    client: mockClients[0],
    consultant_id: "con-001",
    visa_subclass: "482",
    visa_name: "Temporary Skill Shortage",
    stage: "granted",
    priority: "low",
    created_at: daysAgo(120),
    updated_at: daysAgo(30),
    decision_date: daysAgo(30),
    notes_count: 15,
    documents_count: 10,
    documents_pending: 0,
    checklist_progress: 100,
  },
  {
    id: "cs-003",
    client_id: "cl-002",
    client: mockClients[1],
    consultant_id: "con-001",
    visa_subclass: "189",
    visa_name: "Skilled Independent",
    stage: "lodged",
    priority: "medium",
    created_at: daysAgo(25),
    updated_at: daysAgo(5),
    lodgement_date: daysAgo(5),
    notes_count: 6,
    documents_count: 14,
    documents_pending: 0,
    checklist_progress: 100,
  },
  {
    id: "cs-004",
    client_id: "cl-003",
    client: mockClients[2],
    consultant_id: "con-001",
    visa_subclass: "820",
    visa_name: "Partner (Temporary)",
    stage: "documents_collecting",
    priority: "medium",
    created_at: daysAgo(55),
    updated_at: daysAgo(2),
    notes_count: 4,
    documents_count: 8,
    documents_pending: 5,
    checklist_progress: 45,
  },
  {
    id: "cs-005",
    client_id: "cl-004",
    client: mockClients[3],
    consultant_id: "con-001",
    visa_subclass: "186",
    visa_name: "Employer Nomination Scheme",
    stage: "consultation",
    priority: "high",
    created_at: daysAgo(18),
    updated_at: hoursAgo(4),
    notes_count: 3,
    documents_count: 2,
    documents_pending: 2,
    checklist_progress: 15,
  },
  {
    id: "cs-006",
    client_id: "cl-005",
    client: mockClients[4],
    consultant_id: "con-001",
    visa_subclass: "190",
    visa_name: "Skilled Nominated",
    stage: "checklist_sent",
    priority: "medium",
    created_at: daysAgo(12),
    updated_at: daysAgo(1),
    notes_count: 2,
    documents_count: 0,
    documents_pending: 0,
    checklist_progress: 0,
  },
  {
    id: "cs-007",
    client_id: "cl-006",
    client: mockClients[5],
    consultant_id: "con-001",
    visa_subclass: "500",
    visa_name: "Student Visa",
    stage: "lodgement_ready",
    priority: "low",
    created_at: daysAgo(22),
    updated_at: hoursAgo(8),
    notes_count: 5,
    documents_count: 9,
    documents_pending: 0,
    checklist_progress: 100,
  },
  {
    id: "cs-008",
    client_id: "cl-006",
    client: mockClients[5],
    consultant_id: "con-001",
    visa_subclass: "600",
    visa_name: "Visitor Visa",
    stage: "refused",
    priority: "low",
    created_at: daysAgo(90),
    updated_at: daysAgo(60),
    decision_date: daysAgo(60),
    notes_count: 3,
    documents_count: 4,
    documents_pending: 0,
    checklist_progress: 100,
  },
  {
    id: "cs-009",
    client_id: "cl-007",
    client: mockClients[6],
    consultant_id: "con-001",
    visa_subclass: "482",
    visa_name: "Temporary Skill Shortage",
    stage: "intake",
    priority: "urgent",
    created_at: hoursAgo(6),
    updated_at: hoursAgo(2),
    notes_count: 1,
    documents_count: 0,
    documents_pending: 0,
    checklist_progress: 0,
  },
  {
    id: "cs-010",
    client_id: "cl-003",
    client: mockClients[2],
    consultant_id: "con-001",
    visa_subclass: "491",
    visa_name: "Skilled Work Regional",
    stage: "lodged",
    priority: "medium",
    created_at: daysAgo(35),
    updated_at: daysAgo(10),
    lodgement_date: daysAgo(10),
    notes_count: 7,
    documents_count: 11,
    documents_pending: 0,
    checklist_progress: 100,
  },
];

// ── Documents ──
export const mockDocuments: CaseDocument[] = [
  {
    id: "doc-001",
    case_id: "cs-001",
    case_ref: { client_name: "Priya Sharma", visa_subclass: "186" },
    document_type: "Passport",
    file_name: "priya_sharma_passport.pdf",
    uploaded_at: daysAgo(35),
    status: "validated",
    ai_validation: { passed: true, issues: [], confidence: 0.98 },
  },
  {
    id: "doc-002",
    case_id: "cs-001",
    case_ref: { client_name: "Priya Sharma", visa_subclass: "186" },
    document_type: "Skills Assessment",
    file_name: "skills_assessment_ACS.pdf",
    uploaded_at: daysAgo(20),
    status: "validated",
    ai_validation: { passed: true, issues: [], confidence: 0.95 },
  },
  {
    id: "doc-003",
    case_id: "cs-001",
    case_ref: { client_name: "Priya Sharma", visa_subclass: "186" },
    document_type: "English Test (PTE)",
    file_name: "PTE_score_report.pdf",
    uploaded_at: daysAgo(15),
    status: "flagged",
    ai_validation: {
      passed: false,
      issues: ["PTE Overall score 58 — minimum 65 required for subclass 186"],
      confidence: 0.92,
    },
  },
  {
    id: "doc-004",
    case_id: "cs-001",
    case_ref: { client_name: "Priya Sharma", visa_subclass: "186" },
    document_type: "Police Check (AFP)",
    file_name: "AFP_national_check.pdf",
    uploaded_at: daysAgo(10),
    status: "pending",
  },
  {
    id: "doc-005",
    case_id: "cs-003",
    case_ref: { client_name: "Wei Chen", visa_subclass: "189" },
    document_type: "Passport",
    file_name: "wei_chen_passport.pdf",
    uploaded_at: daysAgo(22),
    status: "validated",
    ai_validation: { passed: true, issues: [], confidence: 0.97 },
  },
  {
    id: "doc-006",
    case_id: "cs-003",
    case_ref: { client_name: "Wei Chen", visa_subclass: "189" },
    document_type: "Skills Assessment",
    file_name: "engineers_australia_assessment.pdf",
    uploaded_at: daysAgo(18),
    status: "validated",
    ai_validation: { passed: true, issues: [], confidence: 0.94 },
  },
  {
    id: "doc-007",
    case_id: "cs-004",
    case_ref: { client_name: "James Thompson", visa_subclass: "820" },
    document_type: "Relationship Evidence",
    file_name: "relationship_statement.pdf",
    uploaded_at: daysAgo(8),
    status: "pending",
  },
  {
    id: "doc-008",
    case_id: "cs-004",
    case_ref: { client_name: "James Thompson", visa_subclass: "820" },
    document_type: "Form 888",
    file_name: "form_888_witness_1.pdf",
    uploaded_at: daysAgo(6),
    status: "flagged",
    ai_validation: {
      passed: false,
      issues: ["Witness signature date does not match statutory declaration date"],
      confidence: 0.88,
    },
  },
  {
    id: "doc-009",
    case_id: "cs-005",
    case_ref: { client_name: "Maria Santos", visa_subclass: "186" },
    document_type: "Passport",
    file_name: "maria_santos_passport.pdf",
    uploaded_at: daysAgo(16),
    status: "validated",
    ai_validation: { passed: true, issues: [], confidence: 0.96 },
  },
  {
    id: "doc-010",
    case_id: "cs-005",
    case_ref: { client_name: "Maria Santos", visa_subclass: "186" },
    document_type: "Employment Contract",
    file_name: "employment_contract_2025.pdf",
    uploaded_at: daysAgo(14),
    status: "flagged",
    ai_validation: {
      passed: false,
      issues: ["Contract end date is before visa processing period — may need extension letter"],
      confidence: 0.85,
    },
  },
  {
    id: "doc-011",
    case_id: "cs-007",
    case_ref: { client_name: "Lucas Oliveira", visa_subclass: "500" },
    document_type: "CoE (Confirmation of Enrolment)",
    file_name: "CoE_UNSW_2026.pdf",
    uploaded_at: daysAgo(20),
    status: "validated",
    ai_validation: { passed: true, issues: [], confidence: 0.99 },
  },
  {
    id: "doc-012",
    case_id: "cs-007",
    case_ref: { client_name: "Lucas Oliveira", visa_subclass: "500" },
    document_type: "OSHC (Health Insurance)",
    file_name: "OSHC_allianz_policy.pdf",
    uploaded_at: daysAgo(19),
    status: "validated",
    ai_validation: { passed: true, issues: [], confidence: 0.97 },
  },
];

// ── Dashboard Stats ──
export const mockDashboardStats: DashboardStats = {
  active_cases: 7,
  active_cases_trend: 12,
  documents_pending: 4,
  documents_pending_trend: -8,
  ai_flagged_issues: 3,
  ai_flagged_trend: -15,
  cases_this_month: 3,
  cases_month_trend: 50,
};

// ── Chart Data ──
export const mockCaseActivity: CaseActivityPoint[] = [
  { date: "Mon", cases: 2 },
  { date: "Tue", cases: 5 },
  { date: "Wed", cases: 3 },
  { date: "Thu", cases: 8 },
  { date: "Fri", cases: 6 },
  { date: "Sat", cases: 1 },
  { date: "Sun", cases: 0 },
];

export const mockVisaBreakdown: VisaBreakdownPoint[] = [
  { date: "Mon", skilled: 1, family: 0, student: 1, visitor: 0 },
  { date: "Tue", skilled: 3, family: 1, student: 1, visitor: 0 },
  { date: "Wed", skilled: 2, family: 0, student: 0, visitor: 1 },
  { date: "Thu", skilled: 4, family: 2, student: 1, visitor: 1 },
  { date: "Fri", skilled: 3, family: 1, student: 2, visitor: 0 },
  { date: "Sat", skilled: 1, family: 0, student: 0, visitor: 0 },
  { date: "Sun", skilled: 0, family: 0, student: 0, visitor: 0 },
];

// ── Activity Feed ──
export const mockActivityEntries: ActivityEntry[] = [
  {
    id: "act-001",
    case_id: "cs-009",
    client_name: "Anika Patel",
    action: "classified",
    agent_type: "visa_classifier",
    subject: "New inquiry — Subclass 482 (Temporary Skill Shortage)",
    confidence: 0.92,
    created_at: hoursAgo(2),
    status: "completed",
  },
  {
    id: "act-002",
    case_id: "cs-001",
    client_name: "Priya Sharma",
    action: "flagged",
    agent_type: "document_reviewer",
    subject: "PTE score below minimum threshold for Subclass 186",
    confidence: 0.92,
    created_at: hoursAgo(3),
    status: "flagged",
  },
  {
    id: "act-003",
    case_id: "cs-004",
    client_name: "James Thompson",
    action: "flagged",
    agent_type: "document_reviewer",
    subject: "Form 888 signature date mismatch detected",
    confidence: 0.88,
    created_at: hoursAgo(5),
    status: "flagged",
  },
  {
    id: "act-004",
    case_id: "cs-007",
    client_name: "Lucas Oliveira",
    action: "validated",
    agent_type: "checklist_engine",
    subject: "All Subclass 500 requirements met — ready for lodgement",
    confidence: 0.97,
    created_at: hoursAgo(8),
    status: "completed",
  },
  {
    id: "act-005",
    case_id: "cs-005",
    client_name: "Maria Santos",
    action: "detected",
    agent_type: "intake",
    subject: "New document attachment received via email — Employment Contract",
    confidence: 0.89,
    created_at: hoursAgo(10),
    status: "completed",
  },
  {
    id: "act-006",
    case_id: "cs-003",
    client_name: "Wei Chen",
    action: "classified",
    agent_type: "visa_classifier",
    subject: "Case stage updated to Lodged — Subclass 189",
    confidence: 0.95,
    created_at: daysAgo(1),
    status: "completed",
  },
  {
    id: "act-007",
    case_id: "cs-006",
    client_name: "Soo-jin Kim",
    action: "generated",
    agent_type: "checklist_engine",
    subject: "Checklist generated for Subclass 190 — 14 items",
    confidence: 0.94,
    created_at: daysAgo(1),
    status: "completed",
  },
  {
    id: "act-008",
    case_id: "cs-001",
    client_name: "Priya Sharma",
    action: "validated",
    agent_type: "document_reviewer",
    subject: "Skills Assessment (ACS) — all fields verified",
    confidence: 0.95,
    created_at: daysAgo(2),
    status: "completed",
  },
  {
    id: "act-009",
    case_id: "cs-005",
    client_name: "Maria Santos",
    action: "flagged",
    agent_type: "document_reviewer",
    subject: "Employment contract end date may not cover visa processing period",
    confidence: 0.85,
    created_at: daysAgo(2),
    status: "flagged",
  },
  {
    id: "act-010",
    client_name: "Unknown Sender",
    action: "classified",
    agent_type: "intake",
    subject: "New inquiry email — unable to match to existing client",
    confidence: 0.72,
    created_at: daysAgo(3),
    status: "pending",
  },
];

// ── Inbox Emails ──
export const mockInboxEmails: InboxEmail[] = [
  {
    id: "em-001",
    from_name: "Anika Patel",
    from_email: "anika.p@gmail.com",
    subject: "Visa 482 — sponsorship documents from employer",
    preview: "Hi, my employer has sent through the sponsorship approval letter and the nomination form. I've attached both documents...",
    received_at: hoursAgo(2),
    classification: "Document Submission",
    linked_case_id: "cs-009",
    linked_case_visa: "482",
    linked_client_name: "Anika Patel",
    is_read: false,
    has_attachments: true,
  },
  {
    id: "em-002",
    from_name: "Priya Sharma",
    from_email: "priya.sharma@gmail.com",
    subject: "RE: PTE Score — retake scheduled",
    preview: "Thank you for flagging the PTE score issue. I've booked a retake for next month and will send updated results as soon as...",
    received_at: hoursAgo(5),
    classification: "Case Update",
    linked_case_id: "cs-001",
    linked_case_visa: "186",
    linked_client_name: "Priya Sharma",
    is_read: true,
    has_attachments: false,
  },
  {
    id: "em-003",
    from_name: "James Thompson",
    from_email: "james.t@proton.me",
    subject: "Additional Form 888 witnesses",
    preview: "I have two more friends who can provide Form 888 statutory declarations. Could you send me the template again so I can...",
    received_at: hoursAgo(12),
    classification: "Case Update",
    linked_case_id: "cs-004",
    linked_case_visa: "820",
    linked_client_name: "James Thompson",
    is_read: true,
    has_attachments: false,
  },
  {
    id: "em-004",
    from_name: "Sarah Williams",
    from_email: "sarah.w@outlook.com",
    subject: "Inquiry — Partner Visa 820 process",
    preview: "Hi, I found your firm through the OMARA register. My partner is Australian and we'd like to start the partner visa process. Could you...",
    received_at: daysAgo(1),
    classification: "New Inquiry",
    is_read: false,
    has_attachments: false,
  },
  {
    id: "em-005",
    from_name: "Maria Santos",
    from_email: "maria.santos@yahoo.com",
    subject: "Updated employment contract from employer",
    preview: "As discussed, my employer has extended the contract. Please find the updated version attached with the new end date of...",
    received_at: daysAgo(1),
    classification: "Document Submission",
    linked_case_id: "cs-005",
    linked_case_visa: "186",
    linked_client_name: "Maria Santos",
    is_read: true,
    has_attachments: true,
  },
  {
    id: "em-006",
    from_name: "Department of Home Affairs",
    from_email: "noreply@homeaffairs.gov.au",
    subject: "Request for Information — Application ID 4829103",
    preview: "This is in relation to the visa application lodged for Wei Chen. The Department requires additional information...",
    received_at: daysAgo(2),
    classification: "Government Correspondence",
    linked_case_id: "cs-003",
    linked_case_visa: "189",
    linked_client_name: "Wei Chen",
    is_read: true,
    has_attachments: true,
  },
  {
    id: "em-007",
    from_name: "Unknown",
    from_email: "info@migrationupdate.com.au",
    subject: "Changes to skilled occupation list — effective July 2026",
    preview: "Important update: The Department of Home Affairs has announced changes to the Medium and Long-term Strategic Skills List...",
    received_at: daysAgo(3),
    classification: "Newsletter",
    is_read: false,
    has_attachments: false,
  },
];

// ── Helper: Build journey steps ──
function buildSteps(
  completedUpTo: number,
  currentIdx: number,
  opts?: {
    blockedIdx?: number;
    blockers?: string[];
    notes?: Record<number, string>;
    timestamps?: Record<number, { started?: string; completed?: string }>;
  }
): JourneyStep[] {
  const stageKeys = [
    "inquiry",
    "consultation",
    "visa_pathway",
    "checklist",
    "document_collection",
    "document_review",
    "application_prep",
    "lodgement",
    "post_lodgement",
    "decision",
  ] as const;

  return stageKeys.map((stage, i) => {
    let status: JourneyStep["status"] = "upcoming";
    if (i < completedUpTo) status = "completed";
    else if (i === currentIdx) status = "current";
    if (opts?.blockedIdx === i) status = "blocked";

    const step: JourneyStep = { stage, status };
    if (status === "completed" || status === "current") {
      step.started_at = opts?.timestamps?.[i]?.started ?? daysAgo(45 - i * 4);
    }
    if (status === "completed") {
      step.completed_at =
        opts?.timestamps?.[i]?.completed ?? daysAgo(43 - i * 4);
    }
    if (opts?.notes?.[i]) step.notes = opts.notes[i];
    if (opts?.blockedIdx === i && opts?.blockers)
      step.blockers = opts.blockers;

    return step;
  });
}

// ── Client Journeys ──
export const mockClientJourneys: ClientJourney[] = [
  // cs-001: Priya Sharma — 186 ENS — at document review (stage 6), blocker on PTE score
  {
    case_id: "cs-001",
    client_id: "cl-001",
    visa_subclass: "186",
    visa_name: "Employer Nomination Scheme",
    outcome: null,
    current_stage: "document_review",
    started_at: daysAgo(40),
    updated_at: hoursAgo(3),
    steps: buildSteps(5, 5, {
      blockedIdx: 5,
      blockers: [
        "PTE Overall score 58 — minimum 65 required for subclass 186",
        "AFP police check still pending validation",
      ],
      notes: {
        0: "Referred by existing client Wei Chen",
        1: "Client currently on 482 visa, employer willing to sponsor for 186",
        2: "186 Direct Entry stream confirmed — meets 3-year work experience requirement",
        3: "14-item checklist generated, sent to client via email",
        4: "12 of 14 documents uploaded. PTE score report and AFP check remaining.",
        5: "AI flagged PTE score below threshold. Client has booked retake for next month.",
      },
      timestamps: {
        0: { started: daysAgo(40), completed: daysAgo(40) },
        1: { started: daysAgo(38), completed: daysAgo(36) },
        2: { started: daysAgo(36), completed: daysAgo(34) },
        3: { started: daysAgo(34), completed: daysAgo(32) },
        4: { started: daysAgo(32), completed: daysAgo(15) },
        5: { started: daysAgo(15) },
      },
    }),
  },

  // cs-002: Priya Sharma — 482 TSS — completed & granted
  {
    case_id: "cs-002",
    client_id: "cl-001",
    visa_subclass: "482",
    visa_name: "Temporary Skill Shortage",
    outcome: "granted",
    current_stage: "decision",
    started_at: daysAgo(120),
    updated_at: daysAgo(30),
    steps: buildSteps(10, -1, {
      notes: {
        0: "Initial inquiry for 482 sponsorship",
        2: "482 Medium-term stream — Software Engineer (ANZSCO 261313)",
        7: "Application lodged via ImmiAccount",
        8: "Health examination completed at Bupa Medical. No issues.",
        9: "Visa granted — valid for 4 years from grant date",
      },
      timestamps: {
        0: { started: daysAgo(120), completed: daysAgo(120) },
        1: { started: daysAgo(118), completed: daysAgo(115) },
        2: { started: daysAgo(115), completed: daysAgo(112) },
        3: { started: daysAgo(112), completed: daysAgo(108) },
        4: { started: daysAgo(108), completed: daysAgo(85) },
        5: { started: daysAgo(85), completed: daysAgo(72) },
        6: { started: daysAgo(72), completed: daysAgo(65) },
        7: { started: daysAgo(65), completed: daysAgo(62) },
        8: { started: daysAgo(62), completed: daysAgo(35) },
        9: { started: daysAgo(35), completed: daysAgo(30) },
      },
    }),
  },

  // cs-003: Wei Chen — 189 Skilled Independent — lodged, post-lodgement processing
  {
    case_id: "cs-003",
    client_id: "cl-002",
    visa_subclass: "189",
    visa_name: "Skilled Independent",
    outcome: null,
    current_stage: "post_lodgement",
    started_at: daysAgo(25),
    updated_at: daysAgo(5),
    steps: buildSteps(8, 8, {
      notes: {
        0: "Client referred from partner visa inquiry — redirected to skilled stream",
        2: "189 confirmed — SkillSelect EOI submitted with 75 points. Invitation received.",
        5: "All documents validated by AI. Engineers Australia assessment positive outcome.",
        7: "Application lodged — DHA ref TRN 1234567",
        8: "DHA has issued s56 Request for Information — additional employment references needed",
      },
      timestamps: {
        0: { started: daysAgo(90), completed: daysAgo(90) },
        1: { started: daysAgo(88), completed: daysAgo(85) },
        2: { started: daysAgo(85), completed: daysAgo(80) },
        3: { started: daysAgo(80), completed: daysAgo(75) },
        4: { started: daysAgo(75), completed: daysAgo(45) },
        5: { started: daysAgo(45), completed: daysAgo(30) },
        6: { started: daysAgo(30), completed: daysAgo(20) },
        7: { started: daysAgo(20), completed: daysAgo(15) },
        8: { started: daysAgo(15) },
      },
    }),
  },

  // cs-004: James Thompson — 820 Partner — document collection, blocker on Form 888
  {
    case_id: "cs-004",
    client_id: "cl-003",
    visa_subclass: "820",
    visa_name: "Partner (Temporary)",
    outcome: null,
    current_stage: "document_collection",
    started_at: daysAgo(55),
    updated_at: daysAgo(2),
    steps: buildSteps(4, 4, {
      blockedIdx: 4,
      blockers: [
        "Form 888 witness signature date mismatch — needs re-signing",
        "3 of 8 relationship evidence documents still pending",
      ],
      notes: {
        0: "Client is British citizen, partner is Australian",
        1: "De facto relationship > 2 years. Evidence gathering strategy discussed.",
        2: "820 Partner (Temporary) then 801 Partner (Permanent) pathway confirmed",
        3: "Extensive checklist — 22 items including relationship evidence, financial records, photos, statutory declarations",
        4: "8 of 22 documents uploaded. Form 888 has signature date issue flagged by AI.",
      },
      timestamps: {
        0: { started: daysAgo(55), completed: daysAgo(55) },
        1: { started: daysAgo(52), completed: daysAgo(48) },
        2: { started: daysAgo(48), completed: daysAgo(45) },
        3: { started: daysAgo(45), completed: daysAgo(42) },
        4: { started: daysAgo(42) },
      },
    }),
  },

  // cs-005: Maria Santos — 186 ENS — at consultation stage
  {
    case_id: "cs-005",
    client_id: "cl-004",
    visa_subclass: "186",
    visa_name: "Employer Nomination Scheme",
    outcome: null,
    current_stage: "consultation",
    started_at: daysAgo(18),
    updated_at: hoursAgo(4),
    steps: buildSteps(1, 1, {
      notes: {
        0: "Client currently on 482 visa. Employer interested in permanent sponsorship.",
        1: "Consultation scheduled — discussing TRT vs Direct Entry stream. Employment contract end date flagged as concern.",
      },
      timestamps: {
        0: { started: daysAgo(18), completed: daysAgo(18) },
        1: { started: daysAgo(15) },
      },
    }),
  },

  // cs-006: Soo-jin Kim — 190 Skilled Nominated — checklist sent
  {
    case_id: "cs-006",
    client_id: "cl-005",
    visa_subclass: "190",
    visa_name: "Skilled Nominated",
    outcome: null,
    current_stage: "checklist",
    started_at: daysAgo(12),
    updated_at: daysAgo(1),
    steps: buildSteps(3, 3, {
      notes: {
        0: "Inquiry about state nomination options for ICT Business Analyst",
        1: "NSW and VIC nomination pathways discussed. NSW preferred due to occupation ceiling.",
        2: "190 via NSW nomination confirmed — meets points threshold (70 + 5 state nomination)",
        3: "14-item checklist generated. Waiting for client to begin uploading.",
      },
      timestamps: {
        0: { started: daysAgo(12), completed: daysAgo(12) },
        1: { started: daysAgo(10), completed: daysAgo(8) },
        2: { started: daysAgo(8), completed: daysAgo(6) },
        3: { started: daysAgo(6) },
      },
    }),
  },

  // cs-007: Lucas Oliveira — 500 Student — ready for lodgement (application prep)
  {
    case_id: "cs-007",
    client_id: "cl-006",
    visa_subclass: "500",
    visa_name: "Student Visa",
    outcome: null,
    current_stage: "application_prep",
    started_at: daysAgo(22),
    updated_at: hoursAgo(8),
    steps: buildSteps(6, 6, {
      notes: {
        0: "Student visa inquiry — UNSW Master of IT",
        2: "500 Student Visa confirmed. CoE obtained from UNSW.",
        4: "All documents uploaded: CoE, OSHC, passport, financial evidence, GTE statement",
        5: "AI validation passed all documents. OSHC coverage period verified.",
        6: "Preparing final application package. GTE statement under consultant review.",
      },
      timestamps: {
        0: { started: daysAgo(22), completed: daysAgo(22) },
        1: { started: daysAgo(20), completed: daysAgo(18) },
        2: { started: daysAgo(18), completed: daysAgo(16) },
        3: { started: daysAgo(16), completed: daysAgo(14) },
        4: { started: daysAgo(14), completed: daysAgo(10) },
        5: { started: daysAgo(10), completed: daysAgo(8) },
        6: { started: daysAgo(8) },
      },
    }),
  },

  // cs-008: Lucas Oliveira — 600 Visitor — refused
  {
    case_id: "cs-008",
    client_id: "cl-006",
    visa_subclass: "600",
    visa_name: "Visitor Visa",
    outcome: "refused",
    current_stage: "decision",
    started_at: daysAgo(90),
    updated_at: daysAgo(60),
    steps: buildSteps(10, -1, {
      notes: {
        0: "Visitor visa for initial Australia visit before study",
        2: "600 Tourist stream — 3-month stay",
        7: "Application lodged online",
        8: "No additional requests from DHA",
        9: "Visa refused — insufficient evidence of genuine temporary stay intention. Subsequently applied for Student Visa (500) instead.",
      },
      timestamps: {
        0: { started: daysAgo(90), completed: daysAgo(90) },
        1: { started: daysAgo(88), completed: daysAgo(87) },
        2: { started: daysAgo(87), completed: daysAgo(86) },
        3: { started: daysAgo(86), completed: daysAgo(84) },
        4: { started: daysAgo(84), completed: daysAgo(80) },
        5: { started: daysAgo(80), completed: daysAgo(76) },
        6: { started: daysAgo(76), completed: daysAgo(73) },
        7: { started: daysAgo(73), completed: daysAgo(72) },
        8: { started: daysAgo(72), completed: daysAgo(65) },
        9: { started: daysAgo(65), completed: daysAgo(60) },
      },
    }),
  },

  // cs-009: Anika Patel — 482 TSS — just started, inquiry stage
  {
    case_id: "cs-009",
    client_id: "cl-007",
    visa_subclass: "482",
    visa_name: "Temporary Skill Shortage",
    outcome: null,
    current_stage: "inquiry",
    started_at: hoursAgo(6),
    updated_at: hoursAgo(2),
    steps: buildSteps(0, 0, {
      notes: {
        0: "Urgent inquiry — employer sponsorship documents received. AI classified as 482 TSS. Awaiting consultant assignment.",
      },
      timestamps: {
        0: { started: hoursAgo(6) },
      },
    }),
  },

  // cs-010: James Thompson — 491 Skilled Work Regional — lodged, post-lodgement
  {
    case_id: "cs-010",
    client_id: "cl-003",
    visa_subclass: "491",
    visa_name: "Skilled Work Regional",
    outcome: null,
    current_stage: "post_lodgement",
    started_at: daysAgo(80),
    updated_at: daysAgo(10),
    steps: buildSteps(8, 8, {
      notes: {
        0: "Secondary application — regional skilled pathway as alternative to partner visa timeline",
        2: "491 via SA state nomination — Electrical Engineer (ANZSCO 233311)",
        5: "Skills assessment by Engineers Australia validated. All docs passed AI review.",
        7: "Application lodged — DHA ref TRN 7654321",
        8: "Health examination completed. Waiting for DHA decision. Estimated 6-9 month processing.",
      },
      timestamps: {
        0: { started: daysAgo(80), completed: daysAgo(80) },
        1: { started: daysAgo(78), completed: daysAgo(75) },
        2: { started: daysAgo(75), completed: daysAgo(70) },
        3: { started: daysAgo(70), completed: daysAgo(65) },
        4: { started: daysAgo(65), completed: daysAgo(45) },
        5: { started: daysAgo(45), completed: daysAgo(35) },
        6: { started: daysAgo(35), completed: daysAgo(25) },
        7: { started: daysAgo(25), completed: daysAgo(20) },
        8: { started: daysAgo(20) },
      },
    }),
  },
];
