"""initial schema

Revision ID: 7d1d87c626d8
Revises: 
Create Date: 2026-02-17 23:11:55.246192
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d1d87c626d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_activity_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('mailbox', sa.String(), nullable=True),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_usage_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('summary_time', sa.Time(), nullable=False),
    sa.Column('summary_type', sa.String(), nullable=False),
    sa.Column('total_p1_jobs', sa.Integer(), nullable=True),
    sa.Column('responded_count', sa.Integer(), nullable=True),
    sa.Column('overdue_count', sa.Integer(), nullable=True),
    sa.Column('summary_table', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_summary_date', 'daily_summaries', ['summary_date'], unique=False)
    op.create_index('idx_summary_type', 'daily_summaries', ['summary_type'], unique=False)
    op.create_table('emergent_work_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mailbox', sa.String(), nullable=False),
    sa.Column('source_message_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('contract_reference', sa.String(), nullable=True),
    sa.Column('original_scope_summary', sa.Text(), nullable=True),
    sa.Column('emergent_work_description', sa.Text(), nullable=True),
    sa.Column('supporting_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('processed_attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('raised_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_emergent_client', 'emergent_work_items', ['client_name'], unique=False)
    op.create_index('idx_emergent_status', 'emergent_work_items', ['status'], unique=False)
    op.create_table('emergent_work_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('items_detected', sa.Integer(), nullable=True),
    sa.Column('summary_table', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_detections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mailbox', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('from_email', sa.String(), nullable=False),
    sa.Column('from_name', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_invoice', sa.Boolean(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('attachment_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detected_invoice_type', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('moved_to_folder', sa.String(), nullable=True),
    sa.Column('moved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('manually_reviewed', sa.Boolean(), nullable=True),
    sa.Column('review_action', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index('idx_invoice_is_invoice', 'invoice_detections', ['is_invoice'], unique=False)
    op.create_index('idx_invoice_mailbox', 'invoice_detections', ['mailbox'], unique=False)
    op.create_index('idx_invoice_received', 'invoice_detections', ['received_at'], unique=False)
    op.create_table('p1_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mailbox', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('from_email', sa.String(), nullable=False),
    sa.Column('from_name', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('is_urgent', sa.Boolean(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('contract_location', sa.String(), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('response_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_response_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_responded', sa.Boolean(), nullable=True),
    sa.Column('is_overdue', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index('idx_p1_overdue', 'p1_jobs', ['is_overdue'], unique=False)
    op.create_index('idx_p1_priority', 'p1_jobs', ['priority'], unique=False)
    op.create_index('idx_p1_status', 'p1_jobs', ['status'], unique=False)
    op.create_index('idx_p1_urgent', 'p1_jobs', ['is_urgent'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_p1_urgent', table_name='p1_jobs')
    op.drop_index('idx_p1_status', table_name='p1_jobs')
    op.drop_index('idx_p1_priority', table_name='p1_jobs')
    op.drop_index('idx_p1_overdue', table_name='p1_jobs')
    op.drop_table('p1_jobs')
    op.drop_index('idx_invoice_received', table_name='invoice_detections')
    op.drop_index('idx_invoice_mailbox', table_name='invoice_detections')
    op.drop_index('idx_invoice_is_invoice', table_name='invoice_detections')
    op.drop_table('invoice_detections')
    op.drop_table('emergent_work_reports')
    op.drop_index('idx_emergent_status', table_name='emergent_work_items')
    op.drop_index('idx_emergent_client', table_name='emergent_work_items')
    op.drop_table('emergent_work_items')
    op.drop_index('idx_summary_type', table_name='daily_summaries')
    op.drop_index('idx_summary_date', table_name='daily_summaries')
    op.drop_table('daily_summaries')
    op.drop_table('ai_usage_logs')
    op.drop_table('agent_activity_log')
    # ### end Alembic commands ###
