"""add processed_emails table

Revision ID: 94bb2e42f9f8
Revises: 557d6348aa84
Create Date: 2026-03-21 13:45:05.236176
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94bb2e42f9f8'
down_revision: Union[str, None] = '557d6348aa84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_emails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('mailbox', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_emails_message_id'), 'processed_emails', ['message_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processed_emails_message_id'), table_name='processed_emails')
    op.drop_table('processed_emails')
    # ### end Alembic commands ###
